name       : binutils
version    : 2.31.1
release    : 37
source     :
    - git|git://sourceware.org/git/binutils-gdb.git : dba17838ab20a814e6c8ba51afe6962d1c400227
homepage   : http://gnu.org/
license    : GPL-3.0-or-later
component  :
    - system.devel
    - gold : programming.tools
    - libs : programming.library
summary    :
    - Binutils contains a linker, an assembler, and other tools for handling object files
    - gold : binutils gold linker
    - libs : Runtime libraries for binutils
description: |
    The Binutils package contains a linker, an assembler, and other tools for handling object files.
patterns   :
    - /usr/include
    - /usr/lib64/*.a
    - gold : /usr/bin/ld.gold
    - libs : /usr/lib64/lib*.so*
builddeps  :
    - dejagnu
rundeps    :
    - gold : binutils
setup      : |
    %apply_patches
    buildArch="x86_64-solus-linux"
    mkdir build && pushd build
    ../configure --prefix=/usr \
                 --libdir=%libdir% \
                 --with-lib-path="/usr/lib64:/lib64:/usr/lib32:/lib32" \
                 --enable-lto \
                 --enable-multilib \
                 --enable-gold \
                 --enable-shared \
                 --enable-threads \
                 --disable-gdb \
                 --disable-static \
                 --disable-werror \
                 --enable-deterministic-archives \
                 --enable-plugins \
                 --enable-ld=default \
                 --enable-secureplt \
                 --enable-64-bit-bfd \
                 --target=$buildArch \
                 --build=$buildArch \
                 #--with-system-zlib
build      : |
    %make tooldir=/usr -C build
install    : |
    %make_install tooldir=/usr -C build

    install -m 00644 include/libiberty.h $installdir/usr/include/.
    install -m 00644 build/libiberty/libiberty.a $installdir/%libdir%/.
check      : |
    %make -k check -C build || :
