name       : binutils
version    : 2.29.1
release    : 31
source     :
    - https://ftp.gnu.org/gnu/binutils/binutils-2.29.1.tar.xz : e7010a46969f9d3e53b650a518663f98a5dde3c3ae21b7d71e5e6803bc36b577
homepage   : http://gnu.org/
license    :
    - GPL-3.0
component  :
    - system.devel
    - gold : programming.tools
    - libs : programming.library
summary    :
    - Binutils contains a linker, an assembler, and other tools for handling object files
    - gold : binutils gold linker
    - libs : Runtime libraries for binutils
description: |
    The Binutils package contains a linker, an assembler, and other tools for handling object files.
patterns   :
    - /usr/include
    - /usr/lib64/*.a
    - gold : /usr/bin/ld.gold
    - libs : /usr/lib64/lib*.so*
builddeps  :
    - dejagnu
rundeps    :
    - gold : binutils
setup      : |
    %patch -p1 < $pkgfiles/ld-as-needed.patch
    buildArch="x86_64-solus-linux"
    mkdir build && pushd build
    ../configure --prefix=/usr \
                 --libdir=%libdir% \
                 --with-lib-path="/usr/lib64:/lib64:/usr/lib32:/lib32" \
                 --enable-lto \
                 --enable-multilib \
                 --enable-gold \
                 --enable-shared \
                 --disable-static \
                 --disable-werror \
                 --enable-deterministic-archives \
                 --enable-plugins \
                 --enable-ld=default \
                 --enable-secureplt \
                 --enable-64-bit-bfd \
                 --target=$buildArch \
                 --build=$buildArch
build      : |
    %make tooldir=/usr -C build
install    : |
    %make_install tooldir=/usr -C build

    install -m 00644 include/libiberty.h $installdir/usr/include/.
    install -m 00644 build/libiberty/libiberty.a $installdir/%libdir%/.
check      : |
    %make -k check -C build || :
