name       : binutils
version    : '2.38'
release    : 58
source     :
    - https://github.com/bminor/binutils-gdb/archive/475549dc3acf0736c8e24b1ebe34968e99e2f20a.tar.gz : 232e0253394defeeed457fbb267cac4c1af796872670dccfb9a7be97e97b4ea9
homepage   : http://gnu.org/
license    : GPL-3.0-or-later
component  :
    - system.devel
    - gold : programming.tools
    - libs : programming.library
summary    :
    - Binutils contains a linker, an assembler, and other tools for handling object files
    - gold : binutils gold linker
    - libs : Runtime libraries for binutils
description: |
    The Binutils package contains a linker, an assembler, and other tools for handling object files.
patterns   :
    - /usr/include
    - /usr/lib64/*.a
    - gold : /usr/bin/ld.gold
    - libs : /usr/lib64/lib*.so*
builddeps  :
    - dejagnu
rundeps    :
    - gold : binutils
setup      : |
    sed -i '/^development=/s/true/false/' bfd/development.sh

    %apply_patches
    buildArch="x86_64-solus-linux"
    rm -rf gdb libdecnumber readline sim

    mkdir build && pushd build
    ../configure --prefix=/usr \
                 --libdir=%libdir% \
                 --with-lib-path="/usr/lib64:/lib64:/usr/lib32:/lib32" \
                 --enable-lto \
                 --enable-multilib \
                 --enable-shared \
                 --enable-gold \
                 --enable-threads \
                 --disable-gdb \
                 --disable-gdbserver \
                 --disable-werror \
                 --disable-static \
                 --enable-deterministic-archives \
                 --enable-plugins \
                 --enable-ld=default \
                 --enable-pgo-build=lto \
                 --enable-secureplt \
                 --enable-64-bit-bfd \
                 --target=$buildArch \
                 --build=$buildArch \
                 #--with-system-zlib
build      : |
    %make tooldir=/usr -C build -O
install    : |
    %make_install tooldir=/usr -C build

    install -m 00644 include/libiberty.h $installdir/usr/include/.
    install -m 00644 build/libiberty/libiberty.a $installdir/%libdir%/.
check      : |
    unset LDFLAGS
    %make -k check -C build || :
